In [1]:
import numpy as np

In [3]:
n1=np.zeros((3,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
n2=np.array([[1,2,3],[5,6,7]])
n2

array([[1, 2, 3],
       [5, 6, 7]])

In [6]:
n1_1=np.full((3,5),69)
n1_1


array([[69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69]])

In [7]:
n_range=np.arange(1,20,4)
n_range

array([ 1,  5,  9, 13, 17])

In [13]:
n_random=np.random.rand(3)
n_randomint=np.random.randint(1,50,5)
n_random, n_randomint

(array([0.73726878, 0.19082234, 0.83949832]), array([21, 46, 24, 17, 18]))

In [21]:
n2.shape



(2, 3)

In [22]:
n2.shape=(3,2)

In [23]:
n2


array([[1, 2],
       [3, 5],
       [6, 7]])

In [34]:
nstack1=np.random.randint(1,10,5)
nstack2=np.random.rand(5)
np.vstack((nstack1,nstack2)) ,np.hstack((nstack1,nstack2)) , np.column_stack((nstack1,nstack2))

(array([[5.        , 8.        , 1.        , 8.        , 5.        ],
        [0.03109412, 0.65371079, 0.62298515, 0.75363505, 0.28052543]]),
 array([5.        , 8.        , 1.        , 8.        , 5.        ,
        0.03109412, 0.65371079, 0.62298515, 0.75363505, 0.28052543]),
 array([[5.        , 0.03109412],
        [8.        , 0.65371079],
        [1.        , 0.62298515],
        [8.        , 0.75363505],
        [5.        , 0.28052543]]))

In [44]:
n3=np.array([1,10,5])
n4=np.array([1,20,5])
np.intersect1d(n3,n4),np.setdiff1d(n3,n4), np.setdiff1d(n4,n3)

(array([1, 5]), array([10]), array([20]))

In [47]:
np.sum([n3,n4]), np.sum([n3,n4], axis=0) ,np.sum([n3,n4], axis=1)

(42, array([ 2, 30, 10]), array([16, 26]))

In [49]:
n4/2, n3-1

(array([ 0.5, 10. ,  2.5]), array([0, 9, 4]))

In [53]:
np.std(n4), np.median(n3) , np.mean(n4)

(8.178562764256865, 5.0, 8.666666666666666)

(5.0, 8.666666666666666)